### ISSUE TITLE
Ready for Contribution?

### ISSUE THREAD

**Issue by aunyks** [ethereumjs/ethereumjs-client#11]
Which development stage is the project in? I'd love to contribute.

**Comment by holgerd77** [comment]
Uh oh, I'll try to hurry up a bit if you guys are so eager to start! 👍 🏁 🐰 

I'll do some roundup and clean things up a bit on Monday and Tuesday and hopefully go on to the next phase on Wednesday. We can also rephrase this a bit to "Concept Analysis / Early development", but then please don't start with the most controversial stuff as first PR, hehe.

**Comment by aunyks** [comment]
Oh, there's no need to hurry. Take as much time as you see fit! Just keep me posted ;)

**Comment by holgerd77** [comment]
Officially moved to the next phase, you're the first to be noted 😄. Will write-up some more issues tomorrow and then make an official announcement.

I also reframed the second stage a bit - from "Concept Analysis" to "Concept Analysis / Early Development", think we should already have some common ground for development and it should be possible to carefully to the first development steps. 👟

**Comment by aunyks** [comment]
Awesome! Sounds good
