### ISSUE TITLE
Update test suite / Fix deactivated tests along TypeScript transition

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#147]
Many tests of the library have been deactivated during the `TypeScript` transition #144 to keep the test suite passing. One main problem was the usage of the [testdouble](https://github.com/testdouble/testdouble.js) mockup library, which plays not very well with an `ES6` / `TypeScript` combination. There is some added [ES6 support](https://github.com/testdouble/testdouble.js/blob/master/docs/7-replacing-dependencies.md#how-module-replacement-works-for-es-modules-using-import) in newer versions, but this implies the replacement of the whole Node module loader, which is just too much of an intervention and should be avoided for a test setup here just for the sake of having a mockup library working.

The following is a list of tests being deactivated:

- [ ] [integration/lightsync.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/integration/lightsync.ts)
- [ ] [net/peer/libp2pnode.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/peer/libp2pnode.ts)
- [ ] [net/pper/libp2ppeer.skip (!)](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/peer/libp2ppeer.skip)
- [ ] [net/peer/peer.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/peer/peer.ts)
- [ ] [net/peer/rlpxpeer.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/peer/rlpxpeer.ts)
- [ ] [net/protocol/ethprotocol.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/protocol/ethprotocol.ts)
- [ ] [net/protocol/lesprotocol.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/protocol/lesprotocol.ts)
- [ ] [net/protocol/protocol.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/protocol/protocol.ts)
- [ ] [net/server/libp2pserver.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/server/libp2pserver.ts)
- [ ] [net/server/rlpxserver.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/server/rlpxserver.ts)
- [ ] [net/peerpool.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/net/peerpool.ts)
- [ ] [service/fastethereumservice.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/service/fastethereumservice.ts)
- [ ] [service/lightethereumservice.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/service/lightethereumservice.ts)
- [ ] [sync/sync.ts](https://github.com/ethereumjs/ethereumjs-client/blob/master/test/sync/sync.ts)

These tests should be reactivated over time. 😀

It would be good if this can be done along with having a look and (re-)consider what functionality is actually tested and not just trying to bring everything back to life. Some tests might also be too trivial now in a`TypeScript` environment and it might be more appropriate to just remove. For some tests it might be useful to rather replace with alternative test scenarios than just trying to replicate the old testing functionality.

On the specific `testdouble` issue it might be worth to have a look into alternative mockup libraries (Sinon.js seemed not to be such a suited candidate, see comment [here](https://github.com/ethereumjs/ethereumjs-client/pull/145#issuecomment-702705936)), another way might be to just use manually created / manual mocks where necessary or see what hinders the setup to just use the respective original class.

**Comment by cgewecke** [comment]
Just a status note: am currently working on `lib/blockchain` (integrating the latest monorepo releases). It's not listed above but its dependency problems are (likely) causing the karma tests to fail.

**Comment by holgerd77** [comment]
@cgewecke Ok, have opened an issue #156 to support this and have some reference, had planned to do this anyhow once the releases are out. I've also assigned @rumkin, you should likely coordinate a bit if one of you want to tackle something specific.

**Comment by holgerd77** [comment]
Closed by #182, thanks @ryanio 😄
