### ISSUE TITLE
Integrate @ethereumjs/config v2.0.0 shared configuration 

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#148]
This project has not yet been updated to work with the shared configuration setup from [@ethereumjs/config](https://github.com/ethereumjs/ethereumjs-config), which is also a precondition for #142 

The following updates need to be made (likely as separate PRs):

- [x] `linting`: `standard` -> `@ethereumjs/config-lint` [v2.0.0](https://github.com/ethereumjs/ethereumjs-config/releases/tag/%40ethereumjs%2Flint%402.0.0)
- [x] `typescript`: manual `tsc` invocation and config files -> `@ethereumjs/config-typescript`[v2.0.0](https://github.com/ethereumjs/ethereumjs-config/releases/tag/%40ethereumjs%2Ftypescript%402.0.0)
- [x] `coverage`: coverage scripts -> `@ethereumjs/config-coverage` [v2.0.0](https://github.com/ethereumjs/ethereumjs-config/releases/tag/%40ethereumjs%2Fcoverage%402.0.0)

The respective VM/monorepo PR https://github.com/ethereumjs/ethereumjs-vm/pull/913 can serve as some reference PR here.

**Comment by cgewecke** [comment]
Closing via #151, #152, #153
