### ISSUE TITLE
Add support for Ropsten chain syncing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#15]
#### Description

Currently the client only syncs to the mainnet due to current limitations of the ``ethereumjs-block`` library regarding genesis block creation.

This should in a first step be extended to ``Ropsten`` (as being structurally similar) to lay the groundwork for eventual further expansions (to PoA networks e.g.).

Depends on https://github.com/ethereumjs/ethereumjs-block/pull/44.

**Comment by vpulim** [comment]
Depends on https://github.com/ethereumjs/ethereumjs-blockchain/pull/59. Once that is merged, this issue can be closed.

**Comment by vpulim** [comment]
Closing this since the client now support multiple networks.
