### ISSUE TITLE
Update Monorepo and MPT Dependencies

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#156]
Complementary to #149 

Now that the `beta.1` releases on the monorepo are out along https://github.com/ethereumjs/ethereumjs-vm/pull/922 the respective dependencies can be updated here on the client side (see [package.json](https://github.com/ethereumjs/ethereumjs-client/blob/master/package.json) for an overview). This comes along with the patricia tree (MPT) library to also to be updated.

Following updates necessary:

- [x] Replace [ethereumjs-account](https://github.com/ethereumjs/ethereumjs-vm/pull/922) dependency with the `Util.Account` class from [ethereumjs-util](https://github.com/ethereumjs/ethereumjs-util)
- [x] Update [ethereumjs-blockchain](https://github.com/ethereumjs/ethereumjs-blockchain) `v4.0.4` to `@ethereumjs/blockchain` [v5.0.0-beta.1](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fblockchain%405.0.0-beta.1) or subsequent
- [x] Update [ethereumjs-block](https://github.com/ethereumjs/ethereumjs-block) `v2.0.2` to `@ethereumjs/block` [v3.0.0-beta.1](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fblock%403.0.0-beta.1) or subsequent
- [x] Update [ethereumjs-common](https://github.com/ethereumjs/ethereumjs-common)`v1.5.2` to `@ethereumjs/common` [v2.0.0](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fcommon%402.0.0-beta.1) or subsequent
- [ ] update [merkle-patricia-tree](https://github.com/ethereumjs/merkle-patricia-tree) `v3.0.0` to `v4.0.0`

**Comment by cgewecke** [comment]
Hi @rumkin! 

Just a note in case work might get duplicated...I am pretty far along with an initial attempt at this and will hopefully open a draft PR today which updates block, blockchain, and common.

**Comment by holgerd77** [comment]
Ah, sorry @cgewecke and others, didn't add the MPT library update to the TODO list from above, likely the reason why it was skipped in #158, so will keep this issue open for now. No big deal though, can be updated along a separate PR or some other work.
