### ISSUE TITLE
[META] Chain syncing speed improvements

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#19]
#### Description

Chain syncing works but is still on the slow side. Furthermore there is a particular issue with syncing getting slower after some minutes and coming more-or-less to a halt (might be an issue with peer management/communication in the [ethereumjs-devp2p](https://github.com/ethereumjs/ethereumjs-devp2p), but no proof for this yet).

#### Possible Implementation

Getting chain syncing up to speed will be a constant effort with refinements and optimizations necessary on various fronts. There might be some easy catches to make some larger steps here, but generally this will likely be slow progress over time since gains are hard to get, e.g. by substantial optimizations in the devp2p library.

Nevertheless worth to not let up here and keep on going, since this will be some integral and central part of the client experience (and could also bring substantial improvements for other ``ethereumjs`` libraries along the way).

**Comment by vpulim** [comment]
One way to improve performance is to track RTT (round trip time) and throughput of each peer in order to determine it's capacity. This will allow us to maximize the number of requested headers/blocks from that peer.

See here: https://github.com/ethereum/go-ethereum/blob/master/eth/downloader/peer.go#L262-L321

**Comment by vpulim** [comment]
Closing this out for now since LES flow control has been implemented to maximum header count per request, and fast sync is reasonably fast now (once several peers are found) but speed improvement will be an ongoing goal.
