### ISSUE TITLE
Node discovery v5 implementation

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#2]
Implementation of the new Node discovery protocol, necessary for a reliable light client connection.

See: https://github.com/ethereumjs/ethereumjs-devp2p/issues/19

**Comment by holgerd77** [comment]
Issue has now been funded with a bounty on [GitCoin](https://gitcoin.co/issue/ethereumjs/ethereumjs-devp2p/19/471), work has been started on this.

**Comment by vpulim** [comment]
Closing this issue for now until the v5 spec is finalized and v5 becomes the preferred protocol for other clients.
