### ISSUE TITLE
Separation of LES/ETH network management tasks

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#20]
#### Description

Currently there is some preparation with an ``EthNetworkManager`` subclass in the ``net`` folder, but more or less all the network management tasks and communication is taking place is the generic [NetworkManger](https://github.com/ethereumjs/ethereumjs-client/blob/master/lib/net/NetworkManager.js) class. It should be investigated early on, how this can be separated cleanly between ``LES`` and ``ETH`` communication and especially regarding:

- Which of the logic is generic and can remain in ``NetworkManger`` and which is already ``ETH`` related?
- Are the internal API separations drawn cleanly/is the structure carrying or should logic be shifted or call flow be proceeded in a different way?

It will probably help to start early on with parts of the ``LES`` communication / synchronization to get a feeling where to draw the lines.

**Comment by vpulim** [comment]
See #37
