### ISSUE TITLE
Look to BCOIN for inspiration

### ISSUE THREAD

**Issue by etherai** [ethereumjs/ethereumjs-client#23]
#### Description

See BCOIN for inspiration on project structure / plugin architecture 

#### Possible Implementation

BCOIN

#### UI

BCOIN has a UI framework for building dashboards see bpanel

#### Reference Implementations / Links

https://github.com/bcoin-org/bcoin
http://bcoin.io/bpanel-docs/docs/bpanel-overview.html

**Comment by holgerd77** [comment]
Thanks, not sure how much we can take from there, but really nice for inspiration.

**Comment by dylanbathurst** [comment]
I work at Purse.io, the company that created bcoin/bcash/bpanel etc. I'm happy to make any introductions to the core devs if it would be helpful.

**Comment by holgerd77** [comment]
@dylanbathurst I think we have to think this through more thoroughly if/how far we want to go into this direction or if this might be a separate project cc @vpulim, definitely a gentle offer, thanks!

**Comment by vpulim** [comment]
@etherai, @dylanbathurst There are a lot of good design patterns in bcoin to take inspiration from. Thanks for the pointer.

**Comment by vpulim** [comment]
I've submitted a PR drawing heavy inspiration from bcoin. See here: https://github.com/ethereumjs/ethereumjs-client/pull/37

**Comment by vpulim** [comment]
Closing since #37 has been merged
