### ISSUE TITLE
ethereumjs-devp2p DPT bootstrap error

### ISSUE THREAD

**Issue by ponarunkumar** [ethereumjs/ethereumjs-client#28]
#### Description

/ethereumjs-client$ node lib/index --networkid=3
[ethereumjs-client] 2018-06-08T14:48:49.174Z info: ethereumjs-client initialized
[ethereumjs-client] 2018-06-08T14:48:49.176Z info: Connecting to the ropsten network
[ethereumjs-client] 2018-06-08T14:48:49.180Z info: Initialized data directory: ./chaindb/ropsten
[ethereumjs-client] 2018-06-08T14:48:49.372Z info: Initialized blockchain (current height: 0)
[ethereumjs-client] 2018-06-08T14:48:49.373Z info: Best known block: d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544, TD: 1073741824
[ethereumjs-client] 2018-06-08T14:48:49.373Z info: Started p2p networking communication
[ethereumjs-client] 2018-06-08T14:48:59.379Z error: DPT bootstrap error: Error: Timeout error: ping 13.84.180.240:30303
    at Timeout._onTimeout (/home/appdev/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/dpt/server.js:97:29)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
[ethereumjs-client] 2018-06-08T14:48:59.380Z error: DPT bootstrap error: Error: Timeout error: ping 52.169.14.227:30303
    at Timeout._onTimeout (/home/appdev/ethereumjs-client/node_modules/ethereumjs-devp2p/lib/dpt/server.js:97:29)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
[ethereumjs-client] 2018-06-08T14:49:04.185Z info: Total nodes in DPT: 0, open slots: 25, queue: 0 / 0
[ethereumjs-client] 2018-06-08T14:49:19.196Z info: Total nodes in DPT: 0, open slots: 25, queue: 0 / 0
[ethereumjs-client] 2018-06-08T14:49:34.201Z info: Total nodes in DPT: 0, open slots: 25, queue: 0 / 0
[ethereumjs-client] 2018-06-08T14:49:49.211Z info: Total nodes in DPT: 0, open slots: 25, queue: 0 / 0
[ethereumjs-client] 2018-06-08T14:50:04.215Z info: Total nodes in DPT: 0, open slots: 25, queue: 0 / 0

**Comment by bit-warrior** [comment]
Both(13.84.180.240,52.169.14.227) of the ropsten network bootstrap nodes seems to be unreachable.

**Comment by holgerd77** [comment]
@bit-warrior Thanks for reporting, yes, issue is still open, if you want to submit a PR with the updated nodes from the ``go-ethereum`` file that would be appreciated!

**Comment by holgerd77** [comment]
Not have digged into that to see how to do it - probably emitting an event - but this issue should also be better handled on the ``ethereumjs-devp2p`` side, so that this is not throwing in such an out-of-place error message and can be better handled instead.

Associated code is here: https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/dpt/server.js#L73

**Comment by holgerd77** [comment]
Note: PR has been merged, this still needs a release on the ``ethereumjs-common`` side, otherwise this is solved.

**Comment by vpulim** [comment]
Closing since this looks to be solved.
