### ISSUE TITLE
Its not opening RPC end point waiting for entire syncing to finish.

### ISSUE THREAD

**Issue by bit-warrior** [ethereumjs/ethereumjs-client#39]
#### Description

I am running  node bin/cli.js. Its not opening RPC end point and  waiting for entire syncing to finish.

#### Possible Implementation

https://github.com/ethereumjs/ethereumjs-client/blob/7021bb216572a7c356304df66e05f0cf5c3c3616/bin/cli.js#L91

waiting on this forever before initiating RPC end point

Place this code https://github.com/ethereumjs/ethereumjs-client/blob/7021bb216572a7c356304df66e05f0cf5c3c3616/bin/cli.js#L94

before total sync is fished.

**Comment by vpulim** [comment]
@bit-warrior I was assuming the RPC server shouldn't be run until we had a fully synched blockchain. But I think that was a bad assumption.

I'll submit a fix, but for now, you can make the following change to get unblocked:

https://github.com/ethereumjs/ethereumjs-client/blob/7021bb216572a7c356304df66e05f0cf5c3c3616/bin/cli.js#L65

to:

``node.start()``

**Comment by vpulim** [comment]
https://github.com/ethereumjs/ethereumjs-client/pull/40

**Comment by vpulim** [comment]
Closing. Fixed in #41
