### ISSUE TITLE
Structure and initialization of data directory

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#5]
#### Description

It should be worked out a directly structure where chain and state data is stored, also to be considered is syncing of different networks and light und full sync. This can but doesn't has to be in line with other client implementations.

The data dir has to be initialized at the start of the application, depending on the passed CL options.

#### Possible Implementation

This doesn't necessarily has to be in place from the beginning, can also fall back to a default relative path within the working directory or something. It is more important to have some stubs here which can be completed later.

#### UI

Some CL option ``--datadir`` (can also be in-active at first, see above)

#### Reference Implementations / Links

- [initializeDataDir() function in py-EVM](https://github.com/ethereum/py-evm/blob/master/trinity/chains/__init__.py#L75)

**Comment by kikoncuo** [comment]
From learning how path creation and normalization works from #26 I've done this:

added datadir arg in cliParser.js
recover variable when starting the client
normalize the variable to avoid OS incompatibilities, and update the path to include the chainName.

PR posted.

**Comment by vpulim** [comment]
Fixed in #37
