### ISSUE TITLE
Dependency installation fails on Node 10 / Update leveldown, levelup versions

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#53]
Just tried to reinstall dependencies from within my local GitHub repository with ``npm install`` with Node ``v10.9.0``, this is failing due to an error in the ``leveldown`` installation procedure.

I am not re-stating the error here, I think the issue is that we are in general using pretty outdated (in the library ``^1.9.0``, latest version [v4.0.1](https://github.com/Level/leveldown/releases)) ``leveldown`` and ``levelup`` versions here and also in the [ethereumjs-blockchain](https://github.com/ethereumjs/ethereumjs-blockchain) and [merkle-patricia-tree](https://github.com/ethereumjs/merkle-patricia-tree) libraries.

@vpulim: can you maybe take a look at this on a broader level? I already stumbled on this several times, but I am not really a leveldb expert and can't really judge how much changed throughout the major version updates and how this affects DB compatibility.

**Comment by vpulim** [comment]
@holgerd77 yes, we definitely need to update the levelup/down modules to more recent versions. I believe there was a breaking change in one of the recent versions, but I will take look and try to get the EthereumJS libraries updated.

**Comment by vpulim** [comment]
@pzagor2 Yes, that would be great! Thanks

**Comment by aunyks** [comment]
Happy to see this getting some attention! This error during `npm install` is what kept me from contributing for a while 😅 .

**Comment by vpulim** [comment]
@aunyks Are you still seeing this error? I'm not able to reproduce it using node `10.4.0`

**Comment by aunyks** [comment]
@vpulim I haven't seen it recently since I'm on `v11.1.0`. I was seeing it on `~v8`, however.

**Comment by vpulim** [comment]
Ok thx @aunyks. The [ethereumjs-blockchain](https://github.com/ethereumjs/ethereumjs-blockchain) and [merkle-patricia-tree](https://github.com/ethereumjs/merkle-patricia-tree) libraries have both been updated to use recent versions of `level` modules. I haven't been able to reproduce this with node version 8, 9, 10 or 11 so I'm going to close out this issue.

**Comment by holgerd77** [comment]
Just as a note: ``merkle-patricia-tree`` hasn't been released yet though with the ``level`` DB updates.
