### ISSUE TITLE
Chain Data Synchronization

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-client#6]
#### Description

The client should be able to sync both either block headers (light sync) or block headers and bodies (fast sync) and store both in the DB provided.

It should be possible to abort a sync, syncing should be resumed (light sync) starting with the last canonical block header.

#### Possible Implementation

Syncing has to be done using the appropriate ``ETH`` respectively ``LES`` protocol msgs from the ``ethereumjs-devp2p`` library. As an orientation the [examples](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/examples) over there already provide some guidance on how to get to new block data, this should be more structured though.

There is also the old [node-blockchain-server](https://github.com/ethereumjs/node-blockchain-server/tree/5143e21d146e70e06df6fddaeece2241d6b6e38f) library implementing a very basic syncing logic (just use for orientation on sync logic, the devp2p communication code is outdated).

The [ethereumjs-blockchain](https://github.com/ethereumjs/ethereumjs-blockchain) library can probably be used as a container to keep/extend the blockchain and to manage the DB storage part.

The ``PoW`` verification logic is currently probably not working for the initial blocks due to a fork update on the ``ethereumjs-block`` library (Byzantium). This might have to be adopted and made backwards-compatible again.

#### UI

CL parameter ``--sync-mode``

#### Reference Implementations / Links

- [sync.py](https://github.com/ethereum/py-evm/blob/master/p2p/sync.py) in ``py-EVM``
- [sync.go](https://github.com/ethereum/go-ethereum/blob/master/eth/sync.go), ``go-ethereum``

**Comment by holgerd77** [comment]
Chain syncing is now (basically) working without verification. Will leave this issue open for reference.

**Comment by holgerd77** [comment]
Update: Structure has changes significantly with the introduction of dedicated and separated synchronization strategies, see: https://github.com/ethereumjs/ethereumjs-client/tree/master/lib/sync

**Comment by vpulim** [comment]
Fast sync (header and bodies) and light sync (headers only) are both implemented so I'm closing this out.
