### ISSUE TITLE
Is the eth/63 protocol fully supported yet?

### ISSUE THREAD

**Issue by aunyks** [ethereumjs/ethereumjs-client#80]
#### Description
In [EthProtocol](https://github.com/ethereumjs/ethereumjs-client/blob/master/lib/net/protocol/ethprotocol.js), the list of supported versions includes eth/62 *and* eth/63, but in the file I'm unable to find messages that correspond to [those defined in eth/63](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol#fast-synchronization-pv63).  

Is eth/63 fully supported or is it listed as a protocol version because we support fast sync?

**Comment by aunyks** [comment]
Note: I believe this is closely related to #77.

**Comment by vpulim** [comment]
@aunyks no, I’ve only been adding message definitions to EthProtocol and LesProtocol as needed. Yes, as part of addressing #77, GetNodeData will need to be defined

**Comment by aunyks** [comment]
Cool. I was originally asking because I was going to implement [`eth_protocolVersion`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_protocolversion) and was unsure which protocol version was the latest we support.  

I'll open a PR for that then try to explore going about supporting `eth/63`.

**Comment by vpulim** [comment]
Great. Yes, I think the RPC method should return support for 63
