### ISSUE TITLE
Support contract code in the genesis file

### ISSUE THREAD

**Issue by JohnnySheffield** [ethereumjs/ethereumjs-client#87]
#### Description

* Support contract definitions in the genesis file.
* Calculate correct genesis hash when there are contracts defined in genesis so the chain can be synced.

[Example genesis with a precompiled contract defined](https://github.com/hpoa/lisinski/blob/ee11691c495a82948d30391c03226a46f771a4f8/geth/lisinski.genesis#L809) 

Geth and Parity support this feature. Pantheon and Nethermind have this feature on their todo list.

#### Reference Implementations / Links

Pantheon and Nethermind issues for reference:

https://github.com/PegaSysEng/pantheon/issues/662
https://github.com/NethermindEth/nethermind/issues/338

**Comment by JohnnySheffield** [comment]
Geth calculates "0x5e022e1e3ba4b48b9671ed5182f6442866cf0038acef2ee0ea81de4b86c770d6" for the example genesis file

**Comment by vpulim** [comment]
@JohnnySheffield Sorry for the delay, but the genesis hash should now be computed correctly when there are contracts defined. This was fixed in #94

**Comment by JohnnySheffield** [comment]
Thanks for the update. Will try to sync a ethereumjs node with lisinski testnet and report back here. Cheers!
